#!/bin/sh
function usage() {
cat <<EOF

  Usage: 

  ./StartAll  RUN_TYPE

  where
    - RUN_TYPE    (DQM sources you want to activate): digi, clu, track, all

  Example 1 : ./StartAll  digi
  Example 2 : ./StartAll  clu
  Example 3 : ./StartAll  track
  Example 4 : ./StartAll  all

EOF
}
if [ $# -lt 1 ]; then
  usage; exit 1;
fi

source_type=$1


this="\033[1;31m\033[1m[StartAll]\033[0m - "
if [ "$source_type" == "digi" ]; then
  export PRODUCER_PATH=${CMSSW_BASE}/src/DQM/SiPixelMonitorDigi/test
elif [ "$source_type" == "clu" ]; then
  export PRODUCER_PATH=${CMSSW_BASE}/src/DQM/SiPixelMonitorCluster/test
elif [ "$source_type" == "track" ]; then
  export PRODUCER_PATH=${CMSSW_BASE}/src/DQM/SiPixelMonitorTrack/test
elif [ "$source_type" == "all" ]; then
  export PRODUCER_PATH1=${CMSSW_BASE}/src/DQM/SiPixelMonitorDigi/test
  export PRODUCER_PATH2=${CMSSW_BASE}/src/DQM/SiPixelMonitorCluster/test
  export PRODUCER_PATH3=${CMSSW_BASE}/src/DQM/SiPixelMonitorTrack/test
fi
export CONSUMER_PATH=${CMSSW_BASE}/src/DQM/SiPixelMonitorClient/test

cd ${CONSUMER_PATH}
./StopAll
eval `scramv1 runtime -sh`
COLLECTORNAME=`/bin/hostname`
echo -e "$this Local host: " $COLLECTORNAME

echo -e "$this Starting Collector on xterm" 
xterm -T "DQM Collector"    \
      -tn "DQMCollector"    \
      -sb                   \
      -hold                 \
      -bg "#f1feb6"         \
      -fg black             \
      -sl 100               \
      -geometry 80x20+10+10 \
      -e "DQMCollector" &

cp ${CONSUMER_PATH}/js_files/.svgmap.js ${CONSUMER_PATH}/js_files/svgmap.js
perl -pi.bak -e "s#serverHost#$COLLECTORNAME#g" ${CONSUMER_PATH}/js_files/svgmap.js

if [ "$source_type" == "digi" ]; then
  cp sipixel_monitorelement_config_digi.xml sipixel_monitorelement_config.xml
  cp sipixel_qualitytest_config_digi.xml    sipixel_qualitytest_config.xml
  cd  ${PRODUCER_PATH}
  perl -pi.bak -e "s#DestinationAddress = .+#DestinationAddress = \"$COLLECTORNAME\"#g" sipixel_dqm_source_example.cfg 
  perl -pi.bak -e "s#string\">.+</serverHost>#string\">$COLLECTORNAME</serverHost>#g"   ../../SiPixelMonitorClient/test/.SiPixelWebClient.xml 
  echo -e "$this Starting Producer on xterm" 
  xterm -T "Pixel DQM Digi Source"               \
        -tn "DQMProducer"                        \
        -sb                                      \
        -hold                                    \
        -bg "#d3f2fc"                            \
        -fg black                                \
        -sl 30000                                \
        -geometry 80x20+525+10                   \
        -e "eval `scramv1 runtime -csh`; cmsRun sipixel_dqm_source_example.cfg" &
elif [ "$source_type" == "clu" ]; then
  cp sipixel_monitorelement_config_cluster.xml sipixel_monitorelement_config.xml
  cp sipixel_qualitytest_config_cluster.xml    sipixel_qualitytest_config.xml
  cd  ${PRODUCER_PATH}
  perl -pi.bak -e "s#DestinationAddress = .+#DestinationAddress = \"$COLLECTORNAME\"#g" sipixel_dqm_source_example.cfg 
  perl -pi.bak -e "s#string\">.+</serverHost>#string\">$COLLECTORNAME</serverHost>#g"   ../../SiPixelMonitorClient/test/.SiPixelWebClient.xml 
  echo -e "$this Starting Producer on xterm" 
  xterm -T "Pixel DQM Cluster Source"            \
        -tn "DQMProducer"                        \
        -sb                                      \
        -hold                                    \
        -bg "#d3f2fc"                            \
        -fg black                                \
        -sl 30000                                \
        -geometry 80x20+525+10                   \
        -e "eval `scramv1 runtime -csh`; cmsRun sipixel_dqm_source_example.cfg" &
elif [ "$source_type" == "track" ]; then
  cp sipixel_monitorelement_config_track.xml sipixel_monitorelement_config.xml
  cp sipixel_qualitytest_config_track.xml    sipixel_qualitytest_config.xml
  cd  ${PRODUCER_PATH}
  perl -pi.bak -e "s#DestinationAddress = .+#DestinationAddress = \"$COLLECTORNAME\"#g" SiPixelHitToTrackMon.cfg
  perl -pi.bak -e "s#string\">.+</serverHost>#string\">$COLLECTORNAME</serverHost>#g"   ../../SiPixelMonitorClient/test/.SiPixelWebClient.xml 
  echo -e "$this Starting Producer on xterm" 
  xterm -T "Pixel DQM Residual Source"           \
        -tn "DQMProducer"                        \
        -sb                                      \
        -hold                                    \
        -bg "#d3f2fc"                            \
        -fg black                                \
        -sl 30000                                \
        -geometry 80x20+525+10                   \
        -e "eval `scramv1 runtime -csh`; cmsRun SiPixelHitToTrackMon.cfg" &
elif [ "$source_type" == "all" ]; then
  cp sipixel_monitorelement_config_all.xml sipixel_monitorelement_config.xml
  cp sipixel_qualitytest_config_all.xml    sipixel_qualitytest_config.xml
  cd  ${PRODUCER_PATH1}
  perl -pi.bak -e "s#DestinationAddress = .+#DestinationAddress = \"$COLLECTORNAME\"#g" sipixel_dqm_source_example.cfg
  perl -pi.bak -e "s#string\">.+</serverHost>#string\">$COLLECTORNAME</serverHost>#g"   ../../SiPixelMonitorClient/test/.SiPixelWebClient.xml 
  echo -e "$this Starting Producer on xterm" 
  xterm -T "Pixel DQM Digi Source"               \
        -tn "DQMProducer"                        \
        -sb                                      \
        -hold                                    \
        -bg "#d3f2fc"                            \
        -fg black                                \
        -sl 30000                                \
        -geometry 80x15+525+10                   \
        -e "eval `scramv1 runtime -csh`; cmsRun sipixel_dqm_source_example.cfg" &
  cd  ${PRODUCER_PATH2}
  perl -pi.bak -e "s#DestinationAddress = .+#DestinationAddress = \"$COLLECTORNAME\"#g" sipixel_dqm_source_example.cfg
  perl -pi.bak -e "s#string\">.+</serverHost>#string\">$COLLECTORNAME</serverHost>#g"   ../../SiPixelMonitorClient/test/.SiPixelWebClient.xml 
  echo -e "$this Starting Producer on xterm" 
  xterm -T "Pixel DQM Cluster Source"            \
        -tn "DQMProducer"                        \
        -sb                                      \
        -hold                                    \
        -bg "#d3f2fc"                            \
        -fg black                                \
        -sl 30000                                \
        -geometry 80x15+525+250                   \
        -e "eval `scramv1 runtime -csh`; cmsRun sipixel_dqm_source_example.cfg" &
  cd  ${PRODUCER_PATH3}
  perl -pi.bak -e "s#DestinationAddress = .+#DestinationAddress = \"$COLLECTORNAME\"#g" SiPixelHitToTrackMon.cfg
  perl -pi.bak -e "s#string\">.+</serverHost>#string\">$COLLECTORNAME</serverHost>#g"   ../../SiPixelMonitorClient/test/.SiPixelWebClient.xml 
  echo -e "$this Starting Producer on xterm" 
  xterm -T "Pixel DQM Residual Source"           \
        -tn "DQMProducer"                        \
        -sb                                      \
        -hold                                    \
        -bg "#d3f2fc"                            \
        -fg black                                \
        -sl 30000                                \
        -geometry 80x15+525+470                   \
        -e "eval `scramv1 runtime -csh`; cmsRun SiPixelHitToTrackMon.cfg" &
fi

cd ${CONSUMER_PATH}
echo -e "$this ./setup.sh $COLLECTORNAME"
./setup.sh $COLLECTORNAME
echo -e "$this ./startMonitorClient"
./startMonitorClient 
echo -e "$this Startup finished."
