#!/bin/bash

this="\033[1;33m\033[1m[startMonitorClient]\033[0m - "

echo -e "$this"
echo -e "$this Starting"
eval `scramv1 ru -sh`
xdaq.exe -h lxplus216.cern.ch -p 1972 -e profile.xml &
if ! perl webPingXDAQ.pl lxplus216.cern.ch 1972 10
then
  echo -e "$this xdaq.exe executive didn't start properly"
else
  echo -e "$this xdaq.exe executive started properly"
  perl sendCmdToApp.pl lxplus216.cern.ch 1972 SiPixelWebClient.xml
fi
echo -e "$this Done"
echo -e "$this"

