#!/bin/sh

this="\033[1;34m\033[1m[StopAll]\033[0m - "

echo -e "$this Killing DQMCollector, cmsRun, xdaq.exe"
killall -9 DQMCollector
killall -9 cmsRun
killall -9 xdaq.exe
echo -e "$this Done"

#rm -rf SiPixelWebClient.xml
#rm -rf profile.xml
#rm -rf startMonitorClient


